-- return {
--    'nvim-tree/nvim-tree.lua',
--    dependencies = 'nvim-tree/nvim-web-devicons',
--    config = function()
--       local nvimtree = require 'nvim-tree'
--
--       -- recommended settings from nvim-tree documentation
--       vim.g.loaded_netrw = 1
--       vim.g.loaded_netrwPlugin = 1
--
--       nvimtree.setup {
--          view = {
--             width = 28,
--             relativenumber = true,
--          },
--          -- change folder arrow icons
--          renderer = {
--             indent_markers = {
--                enable = true,
--                icons = {
--                   corner = '└─',
--                   edge = '│ ',
--                   item = '├─',
--                   none = '  ',
--                },
--             },
--             icons = {
--                glyphs = {},
--             },
--          },
--          -- disable window_picker for
--          -- explorer to work well with
--          -- window splits
--          actions = {
--             open_file = {
--                window_picker = {
--                   enable = false,
--                },
--             },
--          },
--          filters = {
--             custom = { '.DS_Store' },
--          },
--          git = {
--             ignore = false,
--          },
--       }
--
--       -- Brighter file names
--       vim.api.nvim_set_hl(0, 'NvimTreeNormal', { fg = '#c8d3f5' })
--       vim.api.nvim_set_hl(0, 'NvimTreeNormalNC', { fg = '#c8d3f5' })
--
--       -- set keymaps
--       local keymap = vim.keymap -- for conciseness
--
--       keymap.set('n', '<leader>ee', '<cmd>NvimTreeToggle<CR>', { desc = 'Toggle file explorer' }) -- toggle file explorer
--       keymap.set('n', '<leader>ef', '<cmd>NvimTreeFindFileToggle<CR>', { desc = 'Toggle file explorer on current file' }) -- toggle file explorer on current file
--       keymap.set('n', '<leader>ec', '<cmd>NvimTreeCollapse<CR>', { desc = 'Collapse file explorer' }) -- collapse file explorer
--       keymap.set('n', '<leader>er', '<cmd>NvimTreeRefresh<CR>', { desc = 'Refresh file explorer' }) -- refresh file explorer
--    end,
-- }

return {}
